services:
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"  # For SSL
    restart: always
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf  # Mount custom NGINX config
      - /etc/letsencrypt/archive/cloud-can-be-only-one.de/:/etc/nginx/ssl     # Mount SSL certificates
    networks:
      - wp_network
    depends_on:
      - wordpress
      - phpmyadmin

  wordpress:
    image: wordpress:latest
    restart: always
    ports:
      - "8081:80"
    environment:
      WORDPRESS_DB_HOST: db  # Ensure this matches the service name
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
      WORDPRESS_DB_NAME: wordpress
    volumes:
      - wordpress_data:/var/www/html
    networks:
      - wp_network
    depends_on:
      - db
    container_name: wordpress_container

  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress
      MYSQL_ROOT_PASSWORD: root_password
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - wp_network
    container_name: mysql_container

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - "8080:80"
    environment:
      PMA_HOST: db  # Use the service name 'db' for MySQL
      MYSQL_ROOT_PASSWORD: root_password
    networks:
      - wp_network
    container_name: phpmyadmin_container

volumes:
  wordpress_data:
  db_data:

networks:
  wp_network:

